# This action is inspired by GitHub's documentation on using Actions for project management.
#
# https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards
#
# It should add newly created tickets to the project board
name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Assign NEW issues to project
        uses: alex-page/github-project-automation-plus@v0.8.1
        #if: github.event.action == 'opened'
        with:
          project: pate
          column: Needs Triage
          action: update
          # Uses lcasburn's personal access token for modifying issues
          # Allows org access to our specific project
          repo-token: ${{ secrets.MY_ORGPROJECT_TOKEN }}
        # Previous workflow is failing with "Parameter token or opts.auth is required", emit the event to understand why
        # Github actions do
      - name: Emit debugging information
        run: |
          echo ${{ github.action }}
          echo ${{ github.event_name }}
          echo ${{ github.ref_type }}
          echo ${{ github.ref }}
          echo ${{ github.event.action }}

