# This action is inspired by GitHub's documentation on using Actions for project management.
#
# https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards
#
# It should add newly created tickets to the project board
name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Assign NEW issues to project
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: pate
          column: Needs Triage
          action: update
          # Use IT generated access token for modifying issues
          repo-token: ${{ secrets.PATE_TEST }}
      - name: Emit debugging information
        if: ${{ failure() }}
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}


